### ISSUE TITLE
For training task model, what does  `img_source img_traget  lab_source lab_target` indicate respectively?

### ISSUE THREAD

**Issue by ksnzh** [lyndonzheng/Synthetic2Realistic#1]

**Comment by lyndonzheng** [comment]
In our task, the `img_source` and `lab_source` indicate the synthetic image and depth respectively, and `img_target` and 'lab_target' indicate the real world image and depth respectively. If you want to do other tasks, you can change the label, like the semantic label.

**Comment by ksnzh** [comment]
If I use the task model and the L1 and smooth loss introduced in the article for supervised depth estimation, will the model achieve the reported score on NYU depth dataset as the f_T-only Benchmark Models shows?

**Comment by lyndonzheng** [comment]
Yes, for task model, you can change the `img_source` to NYU_TRAIN_IMAGE,  `lab_source` to NYU_TRAIN_DEPTH, `img_target` to NYU_TEST_IMAGE, 'lab_target' to NYU_TEST_IMAGE.
