### ISSUE TITLE
Confusion about dataset

### ISSUE THREAD

**Issue by abeyang00** [lyndonzheng/Synthetic2Realistic#10]
I want to make sure i'm getting this correctly,
As i'm aware,
--lab_target_file = Ground truth depth images for real-world domain

I thought we only needed ground truth depth images for synthetic domain.
Where is the lab_target_file used?  Do we need ground truth for real-world data for reconstruction loss?

**Comment by djl11** [comment]
Can you comment what the resolution to this was? I'm having the exact same thought right now.

**Comment by djl11** [comment]
This [comment](https://github.com/lyndonzheng/Synthetic2Realistic/issues/7#issuecomment-426139148) explains it, for anyone else who stumbles onto this issue :)
