### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by abeyang00** [lyndonzheng/Synthetic2Realistic#11]
I get a following error:

RuntimeError: DataLoader worker (pid 10110) is killed by signal: Floating point exception. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

I have set num_workers to 0. but get floating point exception.
What should i do? is it because i have not enough memory?

Code seems to break at
            lab_source = self.transform_augment(lab_source)
inside data_loader.py

Also, I'm using 1080Ti and 12G RAM

**Comment by lyndonzheng** [comment]
I also use a single 1080TI for training the ECCV model, so the problem should not come from the GPU memory.

Can you set the breakpoint for the dataloader process? Most time the problem is coming from the data paths or data format.
