### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by name333** [lyndonzheng/Synthetic2Realistic#17]
Hello 
When I run test.py, the run command is " python test.py --name Outdoor_nyu_wsupervised --model test
--img_source_file /dataset/Image2Depth31_KITTI/testA_SYN80.txt(Synthetic_image)
--img_target_file /dataset/Image2Depth31_KITTI/testA.txt(kitti_image)".
The number of Synthetic_image and kitti_image is 200. I understand running test.py, Synthetic_image to real image, the number of s2t images is 200, and the number of real2depth images should be 200. But when I run, the number of real2depth images is less than 200. Is there any error in understanding the parameters? ? Or there are other things I didn't notice.

**Comment by lyndonzheng** [comment]
@name333 You can read the data_loader.py file. Since the "img_target_path" has two data modes, you need to choose the "paired" mode when you want to test the same number synthtic images and realistic images.
