### ISSUE TITLE
realistic groundtruth depth

### ISSUE THREAD

**Issue by JohannaSpr** [lyndonzheng/Synthetic2Realistic#2]
Could you explain which data from the KITTI (real) dataset exactly you used as realistic groundtruth depth and which preprocessing steps you used?

**Comment by lyndonzheng** [comment]
I obtained the groundtruth depth using the code from 'https://github.com/mrharicot/monodepth'. The data of KITTI also use this  'https://github.com/mrharicot/monodepth/blob/master/utils/kitti_archives_to_download.txt'.
