### ISSUE TITLE
Question about the training set.

### ISSUE THREAD

**Issue by yipengm** [lyndonzheng/Synthetic2Realistic#20]
I found out that the VKITTI dataset includes RGB image in different styles: like clone, fog, etc. I found out that the fog, overcast and rain style looks quite different from the real KITTI dataset. So did you include training sample within those styles? Thank you very much.
![00000](https://user-images.githubusercontent.com/25646118/50872433-bdf86580-138d-11e9-9320-84f9e7ce71fc.png)
![00000](https://user-images.githubusercontent.com/25646118/50872438-c18bec80-138d-11e9-9815-d48d446730c6.png)
![00000](https://user-images.githubusercontent.com/25646118/50872441-c3ee4680-138d-11e9-9218-c3fe3ebd85f7.png)

**Comment by lyndonzheng** [comment]
@yipengm In our original ECCV paper, we just use the normal style images, and ignore the fog, rain style images. I also tried to train the model on these different styles images, the translated network will become unstable in some situations, but the depth estimation performance is very similar to our original results.
