### ISSUE TITLE
scale_pyramid funtion？

### ISSUE THREAD

**Issue by Ariel-JUAN** [lyndonzheng/Synthetic2Realistic#21]
Hi, thanks for sharing the great work. I read the codes and I have something confused...
What does scale_pyramid function do?
`def scale_pyramid(img, num_scales):
    scaled_imgs = [img]

    s = img.size()

    h = s[2]
    w = s[3]

    for i in range(1, num_scales):
        ratio = 2**i
        nh = h // ratio
        nw = w // ratio
        scaled_img = F.upsample(img, size=(nh, nw), mode='bilinear', align_corners=True)
        scaled_imgs.append(scaled_img)

    scaled_imgs.reverse()
    return scaled_imgs`

**Comment by lyndonzheng** [comment]
@Ariel-JUAN Thanks for your interesting. Since the depth estimation network has multi-scale outputs, we use this scale_pyramid function to generate multi-scale ground truth depth for training.
