### ISSUE TITLE
Data preprocessing problem

### ISSUE THREAD

**Issue by drenched9** [lyndonzheng/Synthetic2Realistic#22]
Hello, I noticed that vkitti depth ground truth clippe to 80 m is mentioned in your paper. Can you tell me more details? Or provide a script file for vkitti depth ground truth preprocessing?

**Comment by lyndonzheng** [comment]
@drenched9 The original vkitti depth is 655.35m that stored in 16-bit grayscale PNG images. You just need to read the PNG images and clip the value(value>8000)=8000. Then do the normalization to any data format. In our paper, we store the depth value to 8-bit grayscale images, so we do the normalization value/8000*255. One example is that:
![03030079_b](https://user-images.githubusercontent.com/8929977/50938221-30fafc80-14b2-11e9-8ade-0f12c9473dcb.png)
The original vkitti depth map is that:
![00076](https://user-images.githubusercontent.com/8929977/50938307-92bb6680-14b2-11e9-9454-34f10846b228.png)

**Comment by drenched9** [comment]
Ok, thank you for your reply.
