### ISSUE TITLE
Training only with kitti and virtual kitti

### ISSUE THREAD

**Issue by Sudonuma** [lyndonzheng/Synthetic2Realistic#23]
Hello! 

I am trying to train only using KITTI and VKITTI, 
however whenever I try the train command, I get this error, 

" FileNotFoundError: [Errno 2] No such file or directory: '/data/dataset/Image2Depth_SUN_NYU/trainC.txt' "

I actually don't need the outdoor dataset, 
can you please explain how do I train without the outdoor dataset.
I am new to research and I still find difficulty to understand some stuff.
Thank you!

**Comment by lyndonzheng** [comment]
@Sudonuma  During the training, "trainC.txt" only be used for validation, rather than updating the parameters. If you want to train without this data, you need to modify the code of dataloader.py and T2model.py to remove the lab_target.

**Comment by Sudonuma** [comment]
Hello, Thank you for your response, 
if you don't mind explaining there is something I cannot understand, 
if we are training with kitti, why do we need the indoor dataset here? 

Besides if I don't delete the lab_target how should I do proceed ?
Prepare an NYU data just like we did with Kitti?

**Comment by lyndonzheng** [comment]
Training with KITTI, we only need the vkitti-image, vkitti-depth, kitti-image, kitti-depth(just for validation). The indoor dataset will not be used for training the kitti depth predication task.

**Comment by Sudonuma** [comment]
In this case, why do I get this error every time I try to run the train command if we don't need the NUY dataset? 
Although testing works

error: 
FileNotFoundError: [Errno 2] No such file or directory: '/data/dataset/Image2Depth_SUN_NYU/trainC.txt'
