### ISSUE TITLE
output absolute depth values or normalized ones?

### ISSUE THREAD

**Issue by zengxianyu** [lyndonzheng/Synthetic2Realistic#25]
It seems that net_img2task outputs values in (-1, 1) with a tanh. Then how does the model predict absolute depth value in meter or millimeter for evaluation? I couldn't find the file evaluate.py for evaluation mentioned in README.

**Comment by lyndonzheng** [comment]
@zengxianyu I will store the outputs to RGB image in the range [0, 255]. Then, the util/evaluate.py file is used to evaluate the accuracy. You can find the _load_depth_ function in this file to see how to transform the RGB images to absolute depth value.

**Comment by zengxianyu** [comment]
thank you
