### ISSUE TITLE
Resize problems

### ISSUE THREAD

**Issue by Sudonuma** [lyndonzheng/Synthetic2Realistic#26]
Hello, 
As I have memory issues and my cuda runs out of memory if I surpass batchsize = 3, I needed to resize, but,
I have problems resizing kitti dataset, I actually changed the default loadSize to [256, 192], but it doesn't work, it doesn't work on any size either except for [640, 192],
here is the error I got:
RuntimeError: invalid argument 2: size '[-1 x 245760]' is invalid for input with 589824 elements at /opt/conda/conda-bld/pytorch_1532576128691/work/aten/src/TH/THStorage.cpp:80
Do you have any suggestions of how I could solve this problem?

**Comment by lyndonzheng** [comment]
Dear @Sudonuma If you modify the input size, the feature size for the feature discriminator will be changed . You just need to modify the **model/network.py/_FeatureDiscriminator** input=input.view(-1, 512 * 40 * 12) to input=input.view(-1, 512 * 16 * 12).

**Comment by Sudonuma** [comment]
hello, thanks for your response, in fact I did change that but I still get an error, it starts training then I get this error, 

lab_target_path = self.lab_target_paths[item % self.img_target_size]
IndexError: list index out of range

and this only appears when I resize. do you have any idea of what this could be exactly?
Thank you,
