### ISSUE TITLE
Resize problem

### ISSUE THREAD

**Issue by Sudonuma** [lyndonzheng/Synthetic2Realistic#27]
hello, 
I have asked you previously about the resise resize problem “ issue #26 “, in fact I did change what should be changed but I still get this error message, 

lab_target_path = self.lab_target_paths[item % self.img_target_size]
IndexError: list index out of range

and this only appears when I resize, and in the middle of the training,  do you have any idea of what this could be exactly?
Thank you,

**Comment by lyndonzheng** [comment]
@Sudonuma  For you problem, you can debug the code to see if you have value for the  self.lab_target_paths. Otherwise, the [item % self.img_target_size] should not be out of the range. I have tried to modify the size of the input images, the code runs correctly.

**Comment by Sudonuma** [comment]
Thanks for your response, 
May I know how the number of training images you are using?
