### ISSUE TITLE
How to evalutate Make3d

### ISSUE THREAD

**Issue by jdk9405** [lyndonzheng/Synthetic2Realistic#28]
Hello!
I read your paper very impressively! And I have some questions about Make3D.

At the end of section 4.3 in your paper,  there is a result of Make3D evaluation values.
But when I evaluted the dataset, it does not come out.
Can you tell me more details about it?

1. What is the exact size of depth map(output and ground truth depth map)? 21x305 or 192x640 or others?
2. What is your clipped depth('max_depth') value? 70, 50 or 80?
3. Did you use crop? eigen_crop or garg_crop?

**Comment by lyndonzheng** [comment]
@jdk9405 Thanks for your interesting. 
1. For Make3D, our preditected size of depth map is 192*640. To caculate the evaluation values, we resize the output to the same size as groundtruth.
![image](https://user-images.githubusercontent.com/8929977/58223633-13398000-7d4d-11e9-9279-cc99cbb6bed5.png)
2. We clipped the 'max_depth' to 80 as the KITTI dataset.
3. We didn't use any crop for the Make3D dataset.

**Comment by jdk9405** [comment]
Thank you for your explanation.

**Comment by jdk9405** [comment]
Can you show me the depth map's original color image or jpeg name?
I can't find it in Make3d / Test134 so I wonder if I used wrong images.
