### ISSUE TITLE
Saving the Depth maps 

### ISSUE THREAD

**Issue by koutilya-pnvr** [lyndonzheng/Synthetic2Realistic#33]
https://github.com/lyndonzheng/Synthetic2Realistic/blob/f06db4734b89f80b76f9362ddec17f8eaf1216db/util/evaluation.py#L20

Is there any specific way you are storing the depth maps? 
The output of the Task network has values between -1 and 1. How are you saving those tensors into images? 
In other words, were you using the same names as the input RGB file so that the filename system is coherent during evaluation between the predicted depth maps and GT depth maps?

**Comment by koutilya-pnvr** [comment]
To put it differently, how are you making sure that the predicted depth and the GT depth correspond to the same scene of the test dataset?

**Comment by lyndonzheng** [comment]
For the vKITTI and KITTI training, we just store the depth as 16bit image. During the testing, since we only consider the real world task,  we directly use the sparse depth from the KITTI. For the evaluation, you can follow the [monodepth](https://github.com/mrharicot/monodepth)

**Comment by koutilya-pnvr** [comment]
Right, but if we were to evaluate multiple models, it is very much memory intensive to store all 697 depth images (eigen split) each time. I was thinking of evaluating on the go. Please let me know if I am missing anything in the following steps:

1) Get Real Image and Real Depth (Ground truth) from Kitti dataset 
2) Using the real image, get estimated depth map from the Task model
3) This estimated depth is in range -1 to 1, so add 1 and divide by 2 to make it in the range of 0-1 and then multiply by 80 to correspond for the absolute depth range of 0-80m
4) Once we have the depth tensor, convert it into a numpy array and call the compute_errors function on the Predicted and Ground Truth maps.
5) Get mean statistics over all the 697 samples

Do you think the above works too or is saving the predicted depth maps essential? If one follows the above steps, one may not need to save the predicted depth images.

**Comment by lyndonzheng** [comment]
The depth dense map is necessary for the training. Otherwise, the network can not learn the depth for some depth are correct, some depth are wrong in the ground truth.

Yes, for the evaluation, you can also store the depth as .npy file or other formats.

**Comment by koutilya-pnvr** [comment]
Well I was kind of asking a way around of saving the predicted depth maps (of real images) for evaluation. I was wondering instead of saving these predicted depth maps, what if we directly call the compute_error function using the output of the task model and the real GT depth as arguments. This way we dont even need to save the depth images in the first place and could still perform the evaluation.
