### ISSUE TITLE
Choice of the pool size for the Image history buffer

### ISSUE THREAD

**Issue by koutilya-pnvr** [lyndonzheng/Synthetic2Realistic#34]
https://github.com/lyndonzheng/Synthetic2Realistic/blob/f06db4734b89f80b76f9362ddec17f8eaf1216db/model/T2model.py#L41

How did you go about choosing the pool size for the buffer? What factors would you consider in deciding a particular buffer size? For example the training batch size etc
Because if i recall correctly, the original paper(Simgan) doesn't much talk about the empirical logistics.

**Comment by lyndonzheng** [comment]
@koutilya40192 In SIMGAN, they just focus on the eyes translation, which is an easy task (single object and small region). In our project, we need to translate the full scene for both indoor and outdoor situation. That's we follow the cyclegan to set the pool_size.

**Comment by koutilya-pnvr** [comment]
Thanks for the info, but i am more looking for an answer quantitatively. For example for a batch size of 6, you chose pool_size of 20. My question is did you try out other numbers like pool_size = 40 or 100 or even more? Why did you chose it to be 20? Did you guys have any intuition behind this choice of pool_size for your experiment?

**Comment by lyndonzheng** [comment]
@koutilya40192 Since this is not our novelty, we do not do many experiments on this choice. We just use this trick as cyclegan.

**Comment by koutilya-pnvr** [comment]
Sounds good. Thanks a lot for the response.
