### ISSUE TITLE
SUNCG and NYU

### ISSUE THREAD

**Issue by soundsilence** [lyndonzheng/Synthetic2Realistic#4]
Could you also provide the list of files you use for training on SUNCG and NYU dataset? 

Thanks.

**Comment by lyndonzheng** [comment]
The list of files on SUNCG: [synthetic_file.txt](https://github.com/lyndonzheng/Synthetic2Realistic/files/2385521/synthetic_file.txt). The render code is based on the [SUNCG coder](https://github.com/shurans/SUNCGtoolbox)
The NYUv2 dataset we use the [raw Dataset RGB images](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html), and the standard test list.

**Comment by koutilya-pnvr** [comment]
Can you share the standard train and test list used for NYU depth V2? Sharing a link that has information regarding that would be great. Thanks a lot in advance.
