### ISSUE TITLE
datalists for VKITTI and KITTI

### ISSUE THREAD

**Issue by aasharma90** [lyndonzheng/Synthetic2Realistic#5]
Hi @lyndonzheng 
Is it possible for you to provide us a list of your (train, val, test) datalists for both VKITTI and KITTI datasets respectively? Maybe for the latter, they are \*datasplit/kitti_\*.txt files? Could you please confirm?

**Comment by lyndonzheng** [comment]
Hi @aasharma90 
For VKITTI, we just split the [trainA_SYN.txt](https://github.com/lyndonzheng/Synthetic2Realistic/files/2404234/trainA_SYN.txt) and [testA_SYN.txt](https://github.com/lyndonzheng/Synthetic2Realistic/files/2404233/testA_SYN.txt) for depth estimation. For image-to-image translation video, we choice the very similar scene in VKITTI and KITTI. In this txt file, 03030079_A.png, (_03-03-0079_) represents the '_0001/15-deg-left/00079.png_', and 07120772_A.png (_07-12-0772_) represents the '_0020/sunset/00772.png_'. For the KITTI, just use the standard split.

**Comment by Saurav-31** [comment]
> Hi @aasharma90 For VKITTI, we just split the [trainA_SYN.txt](https://github.com/lyndonzheng/Synthetic2Realistic/files/2404234/trainA_SYN.txt) and [testA_SYN.txt](https://github.com/lyndonzheng/Synthetic2Realistic/files/2404233/testA_SYN.txt) for depth estimation. For image-to-image translation video, we choice the very similar scene in VKITTI and KITTI. In this txt file, 03030079_A.png, (_03-03-0079_) represents the '_0001/15-deg-left/00079.png_', and 07120772_A.png (_07-12-0772_) represents the '_0020/sunset/00772.png_'. For the KITTI, just use the standard split.

Hi @lyndonzheng, How to interpret the codes for vkitti dataset 
`<world>_<variation>_<image_no>` ??  
What I mean is how to know 03 means 15-deg-left? Can you please point me to the that. Thanks in advance.
