### ISSUE TITLE
VRAM requirements?

### ISSUE THREAD

**Issue by aasharma90** [lyndonzheng/Synthetic2Realistic#6]
Hi @lyndonzheng 
I am just trying your translation network, and have removed the task one for now. Could you please advise us how much GPU RAM you are using for your runs? I have a 4-GPU each with 12GB RAM machine, and still cannot load the default loadSize of [256, 192] for KITTI images? The best I can do is [128, 64] (keeping the batchSize=6 as it is) utilizing all the 4 GPUs.

**Comment by lyndonzheng** [comment]
Dear @aasharma90 
During our experiment, we downsample twice for indoor [256\*192 \rightarrow 64\*48] and ourdoor scene [640\*192 \rightarrow 160\*48] on translation network, and then decoder back to the original resolution. Even we use [640\*192] resolution, we can train batchSize=4 for single P100 GPU with 16GB, and batchSize=8 for multi-GPU with 16GB\*2.  For indoor scene with [256\*192], we train both translation network and task network with batchSize=24 (16GB\*2). You have 12GB*4 RAM and only train translation network, I think your bachSize should be larger, not just 6.  

Besides, in our paper, we claim that depth task network can provide geometry information for translation network, that's we say the end-to-end training is important.

**Comment by aasharma90** [comment]
Dear @lyndonzheng 
Yes, unfortunately I am also not able to figure this out. I am using your default settings, so batchSize is indeed 6, and I have 12GB*4 RAM as you mentioned. Still, when I try to go beyond [128, 64], I start getting out of memory errors. If you could please help me, I can contact you separately. 

And yes, I understand why you have the task network. I am just experimenting with your code, and I indeed plan to involve the task network as well, but unfortunately, I am currently struggling with out_of_memory errors, and I am afraid it would worsen if I involve more nets into the procedure. Thanks!

**Comment by lyndonzheng** [comment]
Dear @aasharma90 
Have you tried the latest version we released for multi-GPU? You can first train the original T2Net with both translation network and task network end-to-end to see how many memory it takes.

**Comment by aasharma90** [comment]
Dear @lyndonzheng 
Yes, I think I have your multi-GPU version. I can you some stats from my last experiment (maybe I am doing something incorrect?) -
For --batchSize=6, --model=translation_only (I created a custom net for performing only translation, only for some experiments), --loadSize=[128, 64], --gpu_ids 0,1,2,3
each GPU consumes about ~9.8GB of memory. 

Here is the [train_opt.txt](https://github.com/lyndonzheng/Synthetic2Realistic/files/2404337/train_opt.txt) file, and a snapshot of GPU usage - 
![vram_consumption](https://user-images.githubusercontent.com/27413823/45866786-720cbb00-bdb4-11e8-8a08-0a3a2adf76e9.PNG)

**Comment by lyndonzheng** [comment]
Sorry, since you have modified the code, I cannot say what's the problem. I think you need to run our T2Net with translation and task network to see the memory. If the original code can run larger batchSize, I think you need check your modified code.

**Comment by aasharma90** [comment]
Sure, thanks so much for your help! I am actually trying your complete T2Net now. I'll let you know the outcome.

**Comment by JohannaSpr** [comment]
hey @aasharma90  did you manage to only get the translation network to run?

**Comment by aasharma90** [comment]
Hi @lyndonzheng , @JohannaSpr 
I was able to get the T2Net model work and run within the memory as suggested by @lyndonzheng , but not the translation-only net. This confirms @lyndonzheng 's apprehension that there could be a possible bug in my translation-only code. Unfortunately, I couldn't find time to debug that, and a few experiments I had in mind, I could do them using the T2Net model itself. 

@JohannaSpr, I can share my buggy code if you'd like to see. Just drop me a mail at aashish.sharma@u.nus.edu

@lyndonzheng, Many thanks for your inputs!

**Comment by JohannaSpr** [comment]
When reducing the network one has to set total_loss.backward(retain_graph=True) in backward_synthesis2real() to False! This is default and should only be changed when the loss is passed, as in the original architecture. Otherwise the computed graph won't be freed.
