### ISSUE TITLE
Recurring　 problems

### ISSUE THREAD

**Issue by name333** [lyndonzheng/Synthetic2Realistic#8]
Hello ，
When I run your training code, I will report the following error:
![image](https://user-images.githubusercontent.com/35323680/46791278-5c673180-cd73-11e8-8e92-838384795c07.png).
I only modified the size of the batch, and the thread parameters.
-img_source_file /dataset/Image2Depth31_KITTI/trainA_SYN80.txt
--img_target_file /dataset/Image2Depth31_KITTI/trainA.txt
--lab_source_file /dataset/Image2Depth31_KITTI/trainB_SYN80.txt
--lab_target_file /dataset/Image2Depth31_KITTI/trainB.txt
The images indicated by txt above are all RGB（I also tried to change trainB.txt and trainB_SYN80.txt to grayscale, and the same error occurred.）
So I would like to ask if there is any need for other pre-processing.
Looking forward to your reply ！ｔｈａｎｋｓ !!!

**Comment by lyndonzheng** [comment]
Sorry, for these problems, I cannot help you. I am not sure which part you have modified. You can set some breakpoints to check the code.  In this version, some people have run for unpaired image-to-image translation, and achieved good results. Hence, this code should can be run correct.

**Comment by aasharma90** [comment]
Hi @name333 

From the snapshot you've shared, it looks like that your inputs, lab_fake_i and lab_real_i have different channels, the first being a grayscale tensor([3, **_1_**, 24, 32]), and the second being a color one ([3, **_3_**, 24, 32]). So, you get the error. Could you check when you load your source depth GT, you're loading them in grayscale format only?

**Comment by lyndonzheng** [comment]
@aasharma90 Thanks for answering this questions.

**Comment by lyndonzheng** [comment]
@name333 You can send the detail information (input examples (SYN_A, SYN_B, A, B), train_op.txt, and network structure) to my email. I will check whether I can help you run this code.

**Comment by name333** [comment]
@aasharma90 Hi,hank you for your reply
　　We are loading in RGB format.This part of the code is like this：
![image](https://user-images.githubusercontent.com/35323680/46797190-0ef1c100-cd81-11e8-90ce-c93282ef125c.png)

**Comment by lyndonzheng** [comment]
@name333 For 'lab_source' and 'lab_target', you should not transform them to RGB. Because you output will be 1 channel, this transform will make the groundtruth become 3 channel.

**Comment by aasharma90** [comment]
Hi @name333 , 

Lines no. 47,48 indicate that you are loading your depth GT maps into RGB format, which is incorrect, since the output tensor from the depth network is a grayscale tensor (which you can confirm from the setting of --label_nc argument, which you should see is set to 1). Hence, you get the error. 

I think if you just remove "`.convert('RGB')`" (as it was in the original code), it should be able to work. Hope it helps!

**Comment by name333** [comment]
@aasharma90 
ｔｈａｎｋｓ！
We tried to comment out the .convert('RGB') of lines 47 and 48 before, and the error is the same.

**Comment by aasharma90** [comment]
@name333 , 
Can you simply try printing the size of lab_source and lab_target tensors, and let us know?

**Comment by name333** [comment]
@lyndonzheng 
The error when I commented out this sentence is the same, we have tried many times.
![image](https://user-images.githubusercontent.com/35323680/46798845-ae18b780-cd85-11e8-9615-dfa5166288ef.png)

**Comment by lyndonzheng** [comment]
@name333 Actually, the input and target scale also very strange. Why the size is [24*32]? This is like a feature size. In 'pycharm', you can set some breakpoints, run the code step by step. Then you can check where this error comes from.

**Comment by lyndonzheng** [comment]
@name333 Could you send the code of t2model.py to me? I think you modify some things cause this problem.

**Comment by aasharma90** [comment]
@name333 , 
I think your problem is not that difficult to be debugged. Simply try to observe the dimensions of lab_source tensor (and of the corresponding tensors in the `backward_translated2depth` function) by setting up some breakpoints and/or print statements. Good luck!

**Comment by name333** [comment]
@lyndonzheng 
ｔｈａｎｋｓ!
t2model.py I used the source code you provided, I have already sent you a copy of the mailbox.

**Comment by name333** [comment]
@aasharma90 Thanks for your immediately reply! 
I have been debugging for several days. And I found that when I'm running into the function **backward_translated2depth**,  it returns error. Because **lab_fake_i and lab_real_i** have different channels. And for the code `fake = self.net_img2task.forward(self.img_s2t[-1])`,it inputs a 3 -channel tensor but returns 1-channel tensor! I also trying to look into the **self.net_img2task.forward**, but cannot understand the bottom code.
I'm wondering if you are debugging the code
`fake = self.net_img2task.forward(self.img_s2t[-1])`
your input is a 3-channel and output a 1-channel tensor?

**Comment by name333** [comment]
@aasharma90 @lyndonzheng 
Thanks! the "self.lab_s" is a 3-channel tensor! And I had tried grayscale images, they are 1-channel tensors, but it encountered the same error. As you advised above, I revised lab_source and lab_target images into gray again. 
However, this time it did not return any error but this:
`Process finished with exit code 136 (interrupted by signal 8: SIGFPE)`
I searched on the web, it seems that the ｓtorage is not enough. So I changed the **batch_size=1**, but the code finished as well.
My GPU is 1080 only, is it associated with this?

**Comment by aasharma90** [comment]
@name333 , 
If you are deploying your code on a remote server, please check by running `>> nvidia-smi` on the server to see if it is indeed the memory problem, i.e. the usage is indeed exceeding the available memory

**Comment by aasharma90** [comment]
@name333, 
I think not to over-spam this issue thread, it would be better that we resolve this separately. You can close this issue and drop me a separate mail (enclosing your current error snapshot), and I'll try my best to help you. You can reach out to me at aashish.sharma@u.nus.edu
